### ISSUE TITLE
[ansible] Some code snippets are unreadable

### ISSUE THREAD

**Issue by pkulev** [redconfetti/redconfetti.github.io#4]
Snippets that include jinja variables, I guess, render bad.

Example:
![изображение](https://user-images.githubusercontent.com/1115916/63209428-28724080-c0e9-11e9-8fa6-503c63e795bd.png)

**Comment by redconfetti** [comment]
Hey! I just noticed this issue. Thank you for pointing this out @pkulev

**Comment by redconfetti** [comment]
Okay, I see this is happening on the [Jumpstart Guide to Ansible page](https://www.rubycoloredglasses.com/2019/04/ansible/#ansible-templates). 

[_posts/2019-04-10-ansible.md#L275](https://github.com/redconfetti/redconfetti.github.io/blame/master/_posts/2019-04-10-ansible.md#L275)

**Comment by redconfetti** [comment]
I see that I need to use `{% raw %}` and `{% endraw %}` to ensure that Jekyll doesn't interpret my Jinja templates literally.

https://jinja.palletsprojects.com/en/3.0.x/templates/#escaping
